name: Test all distributions with CRaC

on:
  push:
  workflow_dispatch:

jobs:
  test-java-crac:
    runs-on: ubuntu-latest
  
     
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Download JDK
      run: |
        url=https://cdn.azul.com/zulu/bin/zulu17.44.17-ca-crac-jdk17.0.8-linux_x64.tar.gz
        archive=${url##*/}
        curl -LO $url
        tar -axf $archive
        echo JDK=${archive%%.tar.gz} >> $GITHUB_ENV

    - name: Display JAVA_HOME content
      run: ls -la $JDK/lib/criu


    - name: Verify Java version
      run: java -version

    # - name: Run your tests
    #   run: ./gradlew test  # Replace with your actual test command
