name: Test architecture option

on:
  # push:
  #   branches:
  #     - sapMachine

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [11, 17, 21 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: Shegox/setup-java@main
      with:
        distribution: 'sapmachine'
        java-version: ${{ matrix.java-version }}
        architecture: x86

    - name: Verify Java version
      run: java -version

    