name: Test actions/cache with 'maven', 'gradle', 'sbt'

on:
  # push:
  #   branches:
  #     - sapMachine
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Include macos-latest for all except where overridden
        build-system: ['maven', 'gradle', 'sbt']
        include:
          - build-system: 'sbt'
            os: macos-12 # Override to use macOS-12 specifically for SBT builds
        exclude:
          - build-system: 'sbt'
            os: macos-latest # Exclude macos-latest specifically for SBT builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: Shegox/setup-java@main
        with:
          distribution: 'sapmachine'
          java-version: '21'
          

      - name: Cache Maven packages
        if: matrix.build-system == 'maven'
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-    
      - name: Cache Gradle packages
        if: matrix.build-system == 'gradle'
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
           ${{ runner.os }}-gradle-
      - name: Cache SBT packages
        if: matrix.build-system == 'sbt'
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/build.properties', '**/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build with Maven
        if: matrix.build-system == 'maven'
        run: mvn -B package --file pom.xml 

      - name: Build with Gradle
        if: matrix.build-system == 'gradle'
        run: ./gradlew build --no-daemon

      - name: Build with SBT
        if: matrix.build-system == 'sbt'
        run: sbt package

      - name: Verify Java version
        run: java -version
